theme: jekyll-theme-cayman
title: "Shelley's Data Analyst Portfolio"
description: >- 
  This is my personal portfolio site where I showcase my data analysis projects and skills.
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Skills"
    url: "/skills"
