remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Shelley's Data Analyst Portfolio"
description: >- 
  This is my personal portfolio site where I showcase my data analysis projects and skills.
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Skills"
    url: "/skills"
